---
title: "Evolution of the minimal cell"
author: "Roy Moger-Reischer and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## Making Figure 2: changes in relative fitness

## Clear workspace and set directory
```{r setup}
rm(list=ls())
getwd()
setwd("~/GitHub/MinimalCell")
```

## Load packages and functions
```{r}
require("png")
require("dplyr")
require("grid")
sem <- function(x) sqrt(var(x)/length(x))
```

# Load data
```{r}
# Load data
rel.fit.raw <-read.csv("~/GitHub/MinimalCell/datafiles/Interaction_data_fitness.csv")
rel.fit.raw <- as_tibble(rel.fit.raw)

# Subset data
rel.fit <- rel.fit.raw %>% group_by(timepoint, strain) %>% 
  summarise(mean = mean(W_1.0), sd = sd(W_1.0), sem = sem(W_1.0))

# Set data as factors and rename levels
rel.fit$strain <- as.factor(rel.fit$strain)
levels(rel.fit$strain)[levels(rel.fit$strain)=="JCVI-syn1.0"] <- "Non-minimal"
levels(rel.fit$strain)[levels(rel.fit$strain)=="JCVI-syn3B"] <- "Minimal"
rel.fit$strain <- factor(rel.fit$strain, levels=c("Non-minimal","Minimal"))

# Add x-values for plotting
time.x <- c(1,1,3,3)
rel.fit <- data.frame(rel.fit, time.x)

# Subset relative fitness by strain
rel.fit.wt  <- filter(rel.fit, strain == "Non-minimal") %>%
  dplyr::select(timepoint, mean, sd, sem, time.x)

rel.fit.min  <- filter(rel.fit, strain== "Minimal") %>%
  dplyr::select(timepoint, mean, sd, sem, time.x)
```

## Test significance

```{r}
# Differences in relative fitness between ancestors (wt vs. min)?
# Answer = Yes: t = 11.27, df = 3.1776, p-value = 0.001145
# Minimization led to 52 % reduction in fitness

rel.fit.anc  <- filter(rel.fit.raw, timepoint == "Ancestor") %>%
  dplyr::select(strain, W_1.0)

# Test for equal variance: P = p-value = 0.0462 --> non-homogeneous variance
equal.var.anc <-var.test(rel.fit.anc$W_1.0[1:3], rel.fit.anc$W_1.0[4:7])

test.anc <- t.test(rel.fit.anc$W_1.0 ~ rel.fit.anc$strain, var.equal = F)



# Differences in relative fitness between evolved (wt vs. min)?
# Answer = Yes: t = 11.471, df = 3.19, p-value = 0.001068
# After evolution, minimization has 48 % reduction in fitness

rel.fit.evo  <- filter(rel.fit.raw, timepoint == "Evolved") %>%
  dplyr::select(strain, W_1.0)

# Test for equal variance: P = 0.09 --> homogeneous variance
equal.var.evo <-var.test(rel.fit.evo$W_1.0[1:4], rel.fit.evo$W_1.0[5:8])

test.evo <- t.test(rel.fit.evo$W_1.0 ~ rel.fit.evo$strain, var.equal = T)

# Difference in fitness between minimal and wt after evolution?
# Answer = Yes: t = 5.501, df = 6, p-value = 0.001513



# Differences between fitness of evolved minimal cell and non-evolved ancestor?
test.minvswtanc <- t.test(x=rel.fit.evo$W_1.0[5:8], mu = 1, alternative = 't')
test.minvswtanc
#Difference in fitness between evolved minimal and ancestral non-minimal fitness?
# Answer = No: t = -0.11038, df = 3, p-value = 0.9191


wt.w  <- filter(rel.fit.evo, strain == "JCVI-syn1.0") %>%
  dplyr::select(W_1.0)
wt.delt.w <- wt.w - rel.fit.wt[1,2]

min.w  <- filter(rel.fit.evo, strain == "JCVI-syn3B") %>%
  dplyr::select(W_1.0)
min.delt.w <- min.w - rel.fit.min[1,2]

delta.w <- data.frame(wt.delt.w, min.delt.w)
colnames(delta.w) <-c("Non-minimal", "Minimal")

# Test for equal variance: P = 0.24 --> homogeneous variance
equal.var.delta <- var.test(delta.w$"Non-minimal", delta.w$Minimal)

test.delta <- t.test(delta.w$"Non-minimal", delta.w$Minimal, var.equal = T)

# Does the magnitude of fitness-increase differ between the minimal and the non-minimal populations?
# No, but marginal: t = -2.1567, df = 6, p-value = 0.07441

min.w.fix <- as.numeric(unlist(min.w))
delta.mix  <- min.w.fix - rel.fit.wt[1,2]
delta.mix.mean <- mean(delta.mix)
delta.mix.sem <- sem(delta.mix)
delta.mix.95.UL <- delta.mix.mean + qnorm(0.975) * delta.mix.sem
delta.mix.95.LL <- delta.mix.mean + qnorm(0.025) * delta.mix.sem

delta.min <- delta.w$Minimal
delta.min.mean <- mean(delta.w$Minimal)
delta.min.sem <- sem(delta.w$Minimal)
delta.min.95.UL <- delta.min.mean + qnorm(0.975) * delta.min.sem
delta.min.95.LL <- delta.min.mean + qnorm(0.025) * delta.min.sem

delta.nmin <- delta.w$"Non-minimal"
delta.nmin.mean <- mean(delta.w$"Non-minimal")
delta.nmin.sem <- sem(delta.w$"Non-minimal")
delta.nmin.95.UL <- delta.nmin.mean + qnorm(0.975) * delta.nmin.sem
delta.nmin.95.LL <- delta.nmin.mean + qnorm(0.025) * delta.nmin.sem

png(filename="~/GitHub/MinimalCell/figures/Fig2.Deltas.png",
    width = 1200, height = 1200, res = 96*2) 

par(mar = c(7, 7, 5, 7))

delta.fig <- plot(jitter(rep(1, length(delta.mix)), amount = 0.1), 
      delta.mix, ylim = c(-0.1, 0.7), xlim = c(0.5, 3.5), pch = 21, 
      col = "lightgrey", bg = "lightgrey", lwd = 3.5, cex = 1.7, yaxt = "n", 
      xaxt = "n", cex.lab = 2, cex.axis = 2, las = 1, ylab = "", xlab = "")
      box(lwd = 2)
      
points(jitter(rep(2, length(delta.min)), amount = 0.1), delta.min, 
       pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)

points(jitter(rep(3, length(delta.nmin)), amount = 0.1), delta.nmin, 
       pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)

abline(h= 0, lty = 2, lwd = 1, col="grey")

# Add mean  
points(1, delta.mix.mean, pch = 21, col = "red", 
       bg = "blue", lwd = 3, cex = 2)  
points(2, delta.min.mean, pch = 21, col = "red", 
       bg = "red", lwd = 2, cex = 2)
points(3, delta.nmin.mean, pch = 21, col = "blue", 
       bg = "blue", lwd = 2, cex = 2)


box(lwd = 2)

# Y-axis label # 
mtext(expression('Delta W'), side = 2,
      outer = FALSE, cex = 1.5, line = 3.5, adj = 0.5)

mtext(expression('Ancestor-evolved comparison'), side = 1,
      outer = TRUE, cex = 1.5, line = -2.5, adj = 0.5)

# Major Axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0.0", "0.2", "0.4", "0.6"), at = c(0, 0.2, 0.4, 0.6))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.5, las = 1,
     at=c(-0.2, 0, 0.2, 0.4, 0.6), labels = F, tck = -0.05)
axis(side = 1, lwd.ticks = 2, cex.axis = 1, las = 1,
     labels = c("Min-NonMin", "Min-Min", "Nonmin-Nonmin" ), at = c(1, 2, 3))
axis(side = 3, lwd.ticks = 2, cex.axis = 0.8, las = 1,
     at = c(1, 2, 3), labels = F, tck = -0.05)

# Add confidence intervals 
arrows(x0 = 1, y0 = delta.mix.mean, y1 = delta.mix.95.UL, angle = 90,
       length = 0.15, lwd = 2)
arrows(x0 = 1, y0 = delta.mix.mean, y1 = delta.mix.95.LL, angle = 90,
       length = 0.15, lwd = 2)

arrows(x0 = 2, y0 = delta.min.mean, y1 = delta.min.95.UL, angle = 90,
       length = 0.15, lwd = 2)
arrows(x0 = 2, y0 = delta.min.mean, y1 = delta.min.95.LL, angle = 90,
       length = 0.15, lwd = 2)

arrows(x0 = 3, y0 = delta.nmin.mean, y1 = delta.min.95.UL, angle = 90,
       length = 0.15, lwd = 2)
arrows(x0 = 3, y0 = delta.nmin.mean, y1 = delta.nmin.95.LL, angle = 90,
       length = 0.15, lwd = 2)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/MinimalCell/figures/Fig2.Deltas.png")

grid.raster(img)
```


# Initiate figure
```{r}
png(filename="~/GitHub/MinimalCell/figures/Fig2.png",
    width = 1200, height = 1200, res = 96*2) 

par(mar = c(7, 7, 5, 7))

# initiate plot with points for syn3B ancestor (minimal)
plot(jitter(rep(1, length(rel.fit.anc$W_1.0[1:3])), amount = 0.5), 
     rel.fit.anc$W_1.0[1:3], ylim = c(0.25, 1.65), xlim = c(0, 4.55), 
     pch = 21, bg = "pink", col = "pink", lwd = 2, cex = 1.3, yaxt = "n", 
      xaxt = "n", cex.lab = 1.5, las = 1,  ylab = "", xlab = "")

box(lwd=2)

# add points for for syn 1.0 ancestor (non-minimal)
points(jitter(rep(1, length(rel.fit.anc$W_1.0[4:7])), amount = 0.5), 
       rel.fit.anc$W_1.0[4:7], pch = 21, bg = "lightblue", col = "lightblue", 
       lwd = 2, cex = 1.3)

# add points for syn 3B evolved (minimal)
points(jitter(rep(3, length(rel.fit.evo$W_1.0[5:8])), amount = 0.4), 
       rel.fit.evo$W_1.0[5:8], pch = 21, bg = "pink", col = "pink", 
       lwd = 2, cex = 1.3)

# add points for syn1.0 evolved (non-minimal)
points(jitter(rep(3, length(rel.fit.evo$W_1.0[1:4])), amount = 0.4), 
       rel.fit.evo$W_1.0[1:4], pch = 21, bg = "lightblue", col = "lightblue", 
       lwd = 2, cex = 1.3)

# Add error bars
arrows(x0 = rel.fit.wt$time.x, y0 = rel.fit.wt$mean, 
       y1 = rel.fit.wt$mean + rel.fit.wt$sem, 
       angle = 90, length = 0.1, lwd = 2, col = "blue")
arrows(x0 = rel.fit.wt$time.x, y0 = rel.fit.wt$mean, 
       y1 = rel.fit.wt$mean - rel.fit.wt$sem, 
       angle = 90, length=0.1, lwd = 2, col = "blue")
arrows(x0 = rel.fit.min$time.x, y0 = rel.fit.min$mean, 
       y1 = rel.fit.min$mean + rel.fit.min$sem, 
       angle = 90, length = 0.1, lwd = 2, col = "red")
arrows(x0 = rel.fit.min$time.x, y0 = rel.fit.min$mean, 
       y1 = rel.fit.min$mean - rel.fit.min$sem, 
       angle = 90, length=0.1, lwd = 2, col = "red")

# Add axes and labels
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0.5", "1.0", "1.5"), at = c(0.5, 1, 1.5))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at=c(0.5, 1, 1.5), labels = F)
axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(1, 3), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("Ancestor", "Evolved"), 
     col.axis = "darkgray", at = c(1, 3))
mtext(expression('Time'), side = 1,
      outer = TRUE, cex = 1.5, line = -3.5, adj = 0.45)
mtext(expression("Relative fitness ("~italic("W")~")"), side = 2, 
      outer = TRUE, cex = 1.5, line = -4, adj = 0.55)

# Add line segments
segments(rel.fit.wt$time.x[1], rel.fit.wt$mean[1], rel.fit.wt$time.x[2], 
         rel.fit.wt$mean[2], col = "blue", lwd = 2)
segments(rel.fit.min$time.x[1], rel.fit.min$mean[1], rel.fit.min$time.x[2], 
         rel.fit.min$mean[2], col = "red", lwd = 2)

# Add non-minimal points
points(rel.fit.min$time.x, rel.fit.wt$mean, pch = 22, 
      bg = "blue", col = "blue", lwd = 2, cex = 2)

# Add minimal points
points(rel.fit.min$time.x, rel.fit.min$mean, pch = 22, 
      bg = "red", col = "red", lwd = 2, cex = 2)

# Add P-values
#mtext(expression("Timepoint:" ~italic("P")~"= 0.0003"), line = -2.5, cex = 0.80, at = 0.9)
#mtext(expression("Strain:" ~italic("P")~"< 0.0001"), line = -4.0, cex = 0.80, at = 0.75)

# Add strain identifier
text(3.9, rel.fit.wt$mean[2], labels = "Non-minimal", cex = 1.0)
text(3.9, rel.fit.min$mean[2], labels = "Minimal", cex = 1.0)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/MinimalCell/figures/Fig2.png")

grid.raster(img)
```

# Demonstrate the equations to calculate relative fitness
```{r}
# Load data
calcsheet <-read.csv("~/GitHub/MinimalCell/datafiles/Competition_2019.csv")
calcsheet <- as_tibble(calcsheet)

# Calculate the T0 abundance of the strain-of-interest by subtracting background noise
calcsheet2<-mutate(calcsheet, T0_SOI_calculated=T0_SOI_raw-(T0_Cax_neg/T0_Cax_time*T0_Sampling_time))
# Calc the T24 abundance of the SOI by subtracting background noise. Multiply by 100 to account for dilution difference.
calcsheet3<-mutate(calcsheet2, T24_SOI_calculated=T24_SOI_raw-(T24_Cax_neg/T24_Cax_time*T24_Sampling_time*100))
# Calculate fitness over 24 hr relative to the labeled competitor strain
calcsheet4<-mutate(calcsheet3, W_vs_mCherry_calculated=log(T24_SOI_calculated/T0_SOI_calculated)/log(T24_mCherry/T0_mCherry))
# Divide by the avg fitness of the syn1.0 ancestor
calcsheet5<-mutate(calcsheet4, W_vs_syn1.0anc_calculated= W_vs_mCherry_calculated/1.479025287)
# Divide by the avg fitness of the syn3B ancestor
calcsheet6<-mutate(calcsheet5, W_vs_syn3Banc_calculated= W_vs_mCherry_calculated/0.69419982)
```