---
title: "Evolution of the minimal cell"
author: "Roy Moger-Reischer and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## Making Figure 3: ordination of mutated genes

## Clear workspace and set directory
```{r setup}
rm(list=ls())
getwd()
setwd("~/GitHub/MinimalCell")
```

## Load packages and functions
```{r}
require("png")
require("dplyr")
require("grid")
require("vegan")

```

# Load data
```{r}
# Load data
g.essent.raw <- read.csv("data2/GxP_Mm_essential.csv")
#g.shared.raw <- read.csv("data2/GxP_Mm_all.shared.csv")

g.essent.raw$sample <- as.factor(g.essent.raw$sample)
g.essent.raw$treatment <- as.factor(g.essent.raw$treatment)
levels(g.essent.raw$treatment)[levels(g.essent.raw$treatment)=="s1"] <- "Wildtype"
levels(g.essent.raw$treatment)[levels(g.essent.raw$treatment)=="s3"] <- "Minimal"
g.essent <- as_tibble(g.essent.raw)
g.essent <- as.matrix(g.essent[,3:ncol(g.essent)])
```

# Permutational mulivariate analyis of variance (PERMANOVA)
```{r}
g.essent.adonis <- adonis(g.essent ~ g.essent.raw$treatment, method = "bray", permutations = 9999)

#            Df SumsOfSqs MeanSqs  F.Model  R2        Pr(>F)  
# strain     1   0.95301  0.95301  4.1217   0.40721   0.02857 *
# Residuals  6   1.38731  0.23122           0.59279          
# Total      7   2.34032                    1.00000     
# same qualitative result with Jaccard, Soerensen, Horn, and Kulczynski
```

# Principal Coordinates Analysis (PCoA)
```{r}
# Create a distance matrix

g.essent.dist <- vegdist(g.essent, method = 'bray', upper = TRUE, diag = TRUE)
g.essent.dist <- as_tibble(data.matrix(g.essent.dist))
g.essent.dist.meta <- add_column(g.essent.dist, sample = g.essent.raw$sample, .before = 1)
g.essent.dist.meta <- add_column(g.essent.dist.meta, treatment = g.essent.raw$treatment, .before = 2)
g.essent.dist.meta <- as.matrix(g.essent.dist.meta)

pcoa.eig <- cmdscale(g.essent.dist, eig = TRUE, k = 3)
explainvar1 <- round(pcoa.eig$eig[1] / sum(pcoa.eig$eig), 3) * 100 # 42.1 %
explainvar2 <- round(pcoa.eig$eig[2] / sum(pcoa.eig$eig), 3) * 100 # 16.5 %
explainvar3 <- round(pcoa.eig$eig[3] / sum(pcoa.eig$eig), 3) * 100 # 15.1 %
sum.eig <- sum(explainvar1, explainvar2, explainvar3) # 73 %



g.essent.pcoa <- cmdscale(g.essent.dist, k =3)
g.essent.pcoa <- as.data.frame(g.essent.pcoa)
g.essent.pcoa$treatment <- g.essent.raw$treatment
row.names(g.essent.pcoa) <- g.essent.raw$sample
g.essent.pcoa$sample <- g.essent.raw$sample
names(g.essent.pcoa)[1:3] <- c('PC1', 'PC2', 'PC3')
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "blue", "red",
               "#0072B2", "#D55E00", "#CC79A7")
```

## PCoA Plots
```{r, results = "hide"}

png(filename="~/GitHub/MinimalCell/figures/Fig3.png",
    width = 1200, height = 1200, res = 96*2) 

plot.new()
par(mar = c(7, 7, 5, 7))

plot(g.essent.pcoa[ ,1], g.essent.pcoa[ ,2],
     ylim = c(-1, 1), xlim = c(-0.5, 0.5),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     #xlab = "", ylab = "", xaxt = "n", yaxt = "n",
     pch = 22, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1,
     axes = FALSE)

# Add Axes
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.25, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.25, las = 1)
axis(side = 3, labels = F, lwd.ticks = 2, cex.axis = 1, las = 1, tck=-0.02)
axis(side = 4, labels = F, lwd.ticks = 2, cex.axis = 1, las = 1, tck=-0.02)
axis(side = 1, labels = F, lwd.ticks = 2, cex.axis = 1, las = 1, tck=0.01)
axis(side = 2, labels = F, lwd.ticks = 2, cex.axis = 1, las = 1, tck=0.01)
axis(side = 3, labels = F, lwd.ticks = 2, cex.axis = 1, las = 1, tck=0.01)
axis(side = 4, labels = F, lwd.ticks = 2, cex.axis = 1, las = 1, tck=0.01)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# Subset PCoA scores by strain
essent.wt <- g.essent.pcoa[which(g.essent.pcoa$treatment == "Wildtype"), ]
essent.min <- g.essent.pcoa[which(g.essent.pcoa$treatment == "Minimal"), ]

# Plot points by strain
points(essent.wt[ ,1], essent.wt[ ,2], pch = 21,
       cex = 2, col = "blue", bg = "blue", lwd = 2)

points(essent.min[ ,1], essent.min[ ,2], pch = 21,
       cex = 2, col = "red", bg = "red", lwd = 2)   

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/MinimalCell/figures/Fig3.png")
grid.raster(img)

```
