---
title: "Evolution of the minimal cell"
author: "Roy Moger-Reischer and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## Relative fitness of ftsZ mutants

## Clear workspace and set directory
```{r setup}
rm(list=ls())
getwd()
setwd("~/GitHub/MinimalCell")
```

## Load packages and functions
```{r}
require("png")
require("dplyr")
require("grid")
sem <- function(x) sqrt(var(x)/length(x))
cv <- function(x) (sd(x)/mean(x))*100
```

# Load data
```{r}
# Load data
rel.fit.raw <-read.csv("~/GitHub/MinimalCell/datafiles/ftsZ_W_cases.csv")
rel.fit.raw <- as_tibble(rel.fit.raw)

# Summarize data
rel.fit <- rel.fit.raw %>% group_by(strain, Mutation) %>% 
  summarise(mean = mean(W_1.0), sd = sd(W_1.0), sem = sem(W_1.0), CV = cv(W_1.0))

# Set data as factors and rename levels
rel.fit$strain <- as.factor(rel.fit$strain)
levels(rel.fit$strain)[levels(rel.fit$strain)=="JCVI-syn1.0"] <- "Nonminimal"
levels(rel.fit$strain)[levels(rel.fit$strain)=="JCVI-syn3B"] <- "Minimal"
rel.fit$strain <- factor(rel.fit$strain, levels=c("Nonminimal","Minimal"))

# Add x-values for plotting
time.x <- c(3, 1, 3, 1)
rel.fit <- data.frame(rel.fit, time.x)

# Subset relative fitness by strain
rel.fit.nm  <- filter(rel.fit, strain == "Nonminimal") %>%
  dplyr::select(Mutation, mean, sd, sem, time.x)

rel.fit.m  <- filter(rel.fit, strain== "Minimal") %>%
  dplyr::select(Mutation, mean, sd, sem, time.x)
```

## Tests significance

```{r}
# Two-way ANVOVA

fit1 <- aov(W_1.0 ~ factor(strain) * factor(Mutation), data = rel.fit.raw)
TukeyHSD(fit1)

#                                Df Sum Sq Mean Sq F value  Pr(>F)    
#factor(strain)                   1  4.757   4.757 468.585 < 2e-16 ***
#factor(Mutation)                 1  0.117   0.117  11.524 0.00185 ** 
#factor(strain):factor(Mutation)  1  0.076   0.076   7.453 0.01021 *  
#Residuals                       32  0.325   0.010  

# Comparisons of interest:
#                                       diff        lwr         upr     p adj
# 1. Relative fitness of wild-type strains are different: 
#JCVI-syn3B:None-JCVI-syn1.0:None  -0.65238099 -0.7976860 -0.50707596 0.0000000

# 2. Relative fitness of mutant strains are different:
#JCVI-syn3B:ftsZ-JCVI-syn1.0:ftsZ  -0.84872165 -0.9785498 -0.71889347 0.0000000

# 3. On minimal background, ftsZ mutation has no effect on relative fitness
# JCVI-syn3B:None-JCVI-syn3B:ftsZ   -0.05031722 -0.1617611  0.06112665 0.6169705

# 4. On non-minimal background, ftsZ mutation has no effect on relative fitness
# JCVI-syn1.0:None-JCVI-syn1.0:ftsZ -0.24665788 -0.4064990 -0.08681680 0.0011491

# Percent fitness gain of ftsZ in minimal cell = 14%
# Percent fitness gain of ftsZ in non-minimal cell = 25%
```

# Initiate figure
```{r}
# Make figure
png(filename="./../../../figures/2.extended.data/FigExt3.png",
    width = 1200, height = 1200, res = 96*2) 

plot.new()
par(mar = c(7, 7, 5, 7))

# initiate plot with points for syn3B ancestor (minimal)
plot(jitter(rep(1, length(filter(rel.fit.raw,strain=="JCVI-syn3B" & Mutation=="None")$W_1.0)), amount = 0.5), 
     filter(rel.fit.raw,strain=="JCVI-syn3B" & Mutation=="None")$W_1.0, ylim = c(0.1, 1.75), xlim = c(0, 4.55), 
     pch = 21, bg = "pink", col = "pink", lwd = 2, cex = 1.3, yaxt = "n", 
      xaxt = "n", cex.lab = 1.5, las = 1,  ylab = "", xlab = "")

box(lwd=2)

# add points for for syn 1.0 ancestor (non-minimal)
points(jitter(rep(1, length(filter(rel.fit.raw,strain=="JCVI-syn1.0" & Mutation=="None")$W_1.0)), amount = 0.5), 
       filter(rel.fit.raw,strain=="JCVI-syn1.0" & Mutation=="None")$W_1.0, pch = 21, bg = "lightblue", col = "lightblue", 
       lwd = 2, cex = 1.3)

# add points for for syn 3B ftsZ (minimal)
points(jitter(rep(3, length(filter(rel.fit.raw,strain=="JCVI-syn3B" & Mutation=="ftsZ")$W_1.0)), amount = 0.5), 
       filter(rel.fit.raw,strain=="JCVI-syn3B" & Mutation=="ftsZ")$W_1.0, pch = 21, bg = "pink", col = "pink", 
       lwd = 2, cex = 1.3)

# add points for for syn 3B ftsZ (non-minimal)
points(jitter(rep(3, length(filter(rel.fit.raw,strain=="JCVI-syn1.0" & Mutation=="ftsZ")$W_1.0)), amount = 0.5), 
       filter(rel.fit.raw,strain=="JCVI-syn1.0" & Mutation=="ftsZ")$W_1.0, pch = 21, bg = "lightblue", col = "lightblue", 
       lwd = 2, cex = 1.3)

# Add non-minimal means
points(rel.fit.nm$time.x, rel.fit.nm$mean, pch = 21, 
      bg = "blue", col = "blue", lwd = 2, cex = 2)

# Add minimal means
points(rel.fit.m$time.x, rel.fit.m$mean, pch = 21, 
      bg = "red", col = "red", lwd = 2, cex = 2)

# Add error bars
arrows(x0 = rel.fit.nm$time.x, y0 = rel.fit.nm$mean, 
       y1 = rel.fit.nm$mean + rel.fit.nm$sem, 
       angle = 90, length = 0.1, lwd = 2, col = "blue")
arrows(x0 = rel.fit.nm$time.x, y0 = rel.fit.nm$mean, 
       y1 = rel.fit.nm$mean - rel.fit.nm$sem, 
       angle = 90, length=0.1, lwd = 2, col = "blue")
arrows(x0 = rel.fit.m$time.x, y0 = rel.fit.m$mean, 
       y1 = rel.fit.m$mean + rel.fit.m$sem, 
       angle = 90, length = 0.1, lwd = 2, col = "red")
arrows(x0 = rel.fit.m$time.x, y0 = rel.fit.m$mean, 
       y1 = rel.fit.m$mean - rel.fit.m$sem, 
       angle = 90, length=0.1, lwd = 2, col = "red")

# Add axes and labels
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0.5", "1.0", "1.5"), at = c(0.5, 1, 1.5))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at=c(0.5, 1, 1.5), labels = F)
axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(1, 3), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("Wild type", "ftsZ E315*"), 
     col.axis = "darkgray", at = c(1, 3))
mtext(expression('Strain'), side = 1,
      outer = TRUE, cex = 1.5, line = -3.5, adj = 0.45)
mtext(expression("Relative fitness ("~italic("W")~")"), side = 2, 
      outer = TRUE, cex = 1.5, line = -4, adj = 0.55)

# Add line segments
segments(rel.fit.nm$time.x[1], rel.fit.nm$mean[1], rel.fit.nm$time.x[2], 
         rel.fit.nm$mean[2], col = "blue", lwd = 2)
segments(rel.fit.m$time.x[1], rel.fit.m$mean[1], rel.fit.m$time.x[2], 
         rel.fit.m$mean[2], col = "red", lwd = 2)

# Add P-values
#mtext(expression("Timepoint:" ~italic("P")~"= 0.0003"), line = -2.5, cex = 0.80, at = 0.9)
#mtext(expression("Strain:" ~italic("P")~"< 0.0001"), line = -4.0, cex = 0.80, at = 0.75)

# Add strain identifier
text(3.9, rel.fit.nm$mean[1], labels = "Non-minimal", cex = 1.0)
text(3.8, rel.fit.m$mean[1], labels = "Minimal", cex = 1.0)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("./../../../figures/2.extended.data/FigExt3.png")

grid.raster(img)
```

# Demonstrate the equations to calculate relative fitness
```{r}
# Load data
calcsheet17 <-read.csv("~/GitHub/MinimalCell/datafiles/Competition_2021_strain17.strain16.csv")
calcsheet17 <- as_tibble(calcsheet17)

# Account for the 15 uL volume of inoculum
calcsheet17_2<-mutate(calcsheet17, T0_mCherry_per_inoculated_V_calculated=T0_mCherry_raw_per_10_uL*1.5)
# Account for the 165 uL or 285 uL volume of inoculum
calcsheet17_3<-mutate(calcsheet17_2, T0_SOI_per_inoculated_V_calculated=T0_SOI_raw_per_10_uL*Inoculated_V)
# Account for the difference in dilution factor at T24 sampling
calcsheet17_4<-mutate(calcsheet17_3, T24_mCherry_calculated=T24_mCherry_raw*100)
# Subtract background noise and multiply by 100 to account for difference in dilution
calcsheet17_5<-mutate(calcsheet17_4, T24_SOI_calculated=(T24_SOI_raw-Amount_false_neg_to_subtract_as_proportion_of_true_pos_mCherry_cells*T24_mCherry_raw)*100)
# Calculate fitness relative to the labeled competitor strain
calcsheet17_6<-mutate(calcsheet17_5, W_W_calculated = log(T24_SOI_calculated/T0_SOI_per_inoculated_V_calculated)/log(T24_mCherry_calculated/T0_mCherry_per_inoculated_V_calculated))


calcsheet19 <-read.csv("~/GitHub/MinimalCell/datafiles/Competition_2021_strain19.strain8.csv")
calcsheet19 <- as_tibble(calcsheet19)

# Get the false negatives as a proportion of the true positives
calcsheet19_2<-mutate(calcsheet19, ratio_false_negs_per_true_pos_calculated=mCherry_false_negs_avg/mCherry_true_posvs_avg)
# Account for the 40 uL volume of inoculum
calcsheet19_3<-mutate(calcsheet19_2, T0_mCherry_calculated=T0_mCherry_raw*4)
# Account for the 20 uL volume of inoculum
calcsheet19_4<-mutate(calcsheet19_3, T0_SOI_calculated=T0_SOI_raw*2)
# Multiply by 100 to account for difference in dilution
calcsheet19_5<-mutate(calcsheet19_4, T24_mCherry_calculated=T24_mCherry_raw*100)
# Subtract background noise and multiply by 100 to account for difference in dilution
calcsheet19_6<-mutate(calcsheet19_5, T24_SOI_calculated= (T24_SOI_raw-(ratio_false_negs_per_true_pos_calculated*T24_mCherry_raw))*100)
# Calculate fitness relative to the labeled competitor strain
calcsheet19_7<-mutate(calcsheet19_6, W_W_calculated = log(T24_SOI_calculated/T0_SOI_calculated)/log(T24_mCherry_calculated/T0_mCherry_calculated))
```